# Generated by Django 2.1.7 on 2019-02-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190223_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(max_length=120),
        ),
    ]
