# Generated by Django 2.1.7 on 2019-02-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20190223_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
